modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="unusualprehistory"
version="1.5.0-beta-2"
displayName= "Unusual Prehistory"
logoFile= "examplemod.png"
credits= "Thanks to Fred, Omatypaty, and Crydigo for textures! Thanks to skyjay1#2076 for help on GUI code! Thanks to Scouter456 and Codyy for Coding Help! Thanks to Shroomy and BrayDoesStuff for sound help!"
authors= "Peeko32213"
description='''
A Mod that adds a variety of prehistoric creatures and a way to revive them
'''

[[dependencies.unusualprehistory]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.unusualprehistory]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.geckolib]]
modId="geckolib"
mandatory=true
versionRange="[4.2,)"
ordering="BEFORE"
side="BOTH"

